{% set version = "1.0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sqn
  version: {{ version|replace("-", "_") }}

source:
  fn: SQN_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/SQN_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SQN/SQN_{{ version }}.tar.gz
  sha256: 17deaa02b4fc71120b15435654ebadac0ab48abc6524616d81cdfc8e5a24f0dc

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-mclust >=3.2
    - r-nor1mix >=1.0_7
  run:
    - r-base
    - r-mclust >=3.2
    - r-nor1mix >=1.0_7

test:
  commands:
    - $R -e "library('SQN')"           # [not win]
    - "\"%R%\" -e \"library('SQN')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SQN
  license: LGPL (>= 2.0)
  summary: Normalization based a subset of negative control probes as described in 'Subset quantile normalization using negative control features'. Wu Z, Aryee MJ, J Comput Biol. 2010 Oct;17(10):1385-95 [PMID 20976876].
  license_family: LGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
