appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: mgEr9yzZ2JLIgUahhnImmV1eif/5RwE6J+92I9gKN60UIU3f2AYOKOabOq0t6iKuLGUOnYr0AS9ZLu6hLrzM3jGw26uDL2P4e1VRzw5fCCkpulSMCox66L3OMETZUnI8xDKhamO7T1B84qKA3WgJjibS26PapKllwhnazgCm0vbI8iI7HLAEDnY14igGlNA1TcQlYscPqCZQDyQMWJ9BjxYYHND8JhISIp5A9VHj6Hq5DHlq8yV0incMIXpsO4Vic1WOMBdkCY+k+1Zit4S9rps3ycrsOIuMzwCmvyH1wJI2FIBImP5E1wf0QtISTvpymewCVR+6HfaQhCkwypRF/BAUsR3Y2YEHKXVHnvaAIuWysCELQz/d58rlMzJVpdk4oWzqXHMSanjQ4oKY/cZC8qzrp3JVKwEW+h9ZC9DDxXmZEdL8hneZopzSsg4UN1Yn0+jkUmPS+KhgzhrhEwLdKyZzdpVUwajMHjPzfwi9WY5I/uDn5L1AF6gucK4uVk0H44qVx2egXhAyP4RzVmb/zveoHPcPFYpF3salSdkzXut7pnRrv4vUrv6x7PO3LeIaUd3zkSFA0wLYeKpigDNVIXa8B7b0LwE4Lm4VfWWGip9vIZhpZrwr9frG6/s9VkXHVB/OQlr7qNXyOmxpcanXOAzjhe6U/V3XFqAxSjgRvqg=}
bot:
  automerge: true
